app:
  name: vodafone-ziggo-demo

container:
  name: devops-challenge

replicaCount: 1

image:
  repository: shrushti5/devops-challenge
  tag: fd11cc50d0aca03c2b9f06a61d630f1ff2bd6c8b

service:
  port: 8080
  targetPort: 8080

host:
  name: devops.localhost