app:
  name: vodafone-ziggo-demo

container:
  name: devops-challenge

replicaCount: 1

image:
  repository: shrushti5/devops-challenge
  tag: a438cc311b7c1907f2c4f2a5948fd4db979fb1c8

service:
  port: 8080
  targetPort: 8080

host:
  name: devops.localhost