app:
  name: vodafone-ziggo-demo

container:
  name: devops-challenge

replicaCount: 1

image:
  repository: shrushti5/devops-challenge
  tag: 9994fe472110b77ae72fb474cf56e6f9bdfa6d6d

service:
  port: 8080
  targetPort: 8080