apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-challenge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ShrushtiK/devops-challenge.git
    targetRevision: argo-cd
    path: helm/webserver
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-challenge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true